### ISSUE TITLE
Question: Is the summary supposed to be a copy of a paragraph from original text ?

### ISSUE THREAD

**Issue by isocroft** [Emekaborisama/summarizerapi#8]
I recently tried the **_@summarizedthread_** bot on **Twitter** on the tweet below and found out that it only selected a paragraph from the original tweet and made it the summary result as you can see. Is this the way it’s supposed to work ?

I don’t think this is the way it ought to work though

![2CDAB7E3-AAE7-4611-A634-244AA6F5A8A4](https://user-images.githubusercontent.com/5495952/113197638-cf730400-925c-11eb-9aa6-8b0637175798.jpeg)

**Comment by Emekaborisama** [comment]
That's how it's supposed to work. basically, we have two kinds of summarization; Abstractive and extractive. To ensure we retain the user contents and also we don't rewrite someone's content without his or her permission, we decided to use an Extractive summarizer
